services:
  postgres:
    image: postgres:15.0
    environment:
      POSTGRES_DB: "arithmeticCalculator"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"